/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class insights_water_waterinsightsv005_CvUtil */

#ifndef _Included_insights_water_waterinsightsv005_CvUtil
#define _Included_insights_water_waterinsightsv005_CvUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    loadImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_insights_water_waterinsightsv005_CvUtil_loadImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    processImage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_insights_water_waterinsightsv005_CvUtil_processImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    DEBUG_DRAW_REFERENCE
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_insights_water_waterinsightsv005_CvUtil_DEBUG_1DRAW_1REFERENCE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    DEBUG_DRAW_SAMPLE
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_insights_water_waterinsightsv005_CvUtil_DEBUG_1DRAW_1SAMPLE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    DEBUG_DRAW_TARGET
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_insights_water_waterinsightsv005_CvUtil_DEBUG_1DRAW_1TARGET
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
