/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class insights_water_waterinsightsv005_CvUtil */

#ifndef _Included_insights_water_waterinsightsv005_CvUtil
#define _Included_insights_water_waterinsightsv005_CvUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    loadImage
 * Signature: (Ljava/lang/String;I)Ljava/util/ArrayList;
 */
JNIEXPORT jfloatArray JNICALL Java_insights_water_waterinsightsv005_CvUtil_loadImage
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    getStep1Code
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_insights_water_waterinsightsv005_CvUtil_getStep1Code
  (JNIEnv *, jclass);

/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    getStep2Code
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_insights_water_waterinsightsv005_CvUtil_getStep2Code
  (JNIEnv *, jclass);

/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    getStep3Code
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_insights_water_waterinsightsv005_CvUtil_getStep3Code
  (JNIEnv *, jclass);

/*
 * Class:     insights_water_waterinsightsv005_CvUtil
 * Method:    getStep4Code
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_insights_water_waterinsightsv005_CvUtil_getStep4Code
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
