/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class insights_water_waterinsightsV005_CvUtil */

#ifndef _Included_insights_water_waterinsightsv005_CvUtil
#define _Included_insights_water_waterinsightsv005_CvUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     insights_water_waterinsightsV005002_CvUtil
 * Method:    processImage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_insights_water_waterinsightsv005_CvUtil_processImage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
